#!/bin/bash


while read oldrev newrev ref
do
 if [[ $ref =~ .*/main$ ]];
 then
 echo "Master ref received. Deploying master branch to production..."
 sudo git --work-tree=/model_serving --git-dir=/home/appuser/incoming_deploy checkout -f main
  
 cd /model_serving/dev
 sudo chmod +x train.sh
 ./train.sh
 
 else
 echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
 fi
done