#!/bin/bash
cp best_model.pt /home/appuser/outgoing_deploy/best_model.pt
cd /home/appuser/outgoing_deploy
echo "Adding changes to Git repository..."
git add . || { echo "Git add failed"; exit 1; }
git commit -m "New model deployed to production"
git push prod master