#!/bin/bash
while read oldrev newrev ref
do
 if [[ $ref =~ .*/master$ ]];
 then
 echo "Master ref received. Deploying master branch to production..."
 sudo git --work-tree=/model_serving/prod --git-dir=/home/appuser/incoming_deploy checkout -f
 else
 echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
 fi
done