version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.ssh/cluster-key:/app/cluster-key
    env_file:
      - .env
    network_mode: host
