- name: Set up SSH access from one host to another
  hosts: devserver
  tasks:
    - name: Check if SSH key already exists
      stat:
        path: ~/.ssh/id_rsa.pub
      register: ssh_key

    - name: Generate SSH key
      command: ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ''
      when: not ssh_key.stat.exists

    - name: Get the public key
      command: cat ~/.ssh/id_rsa.pub
      register: ssh_pub_key

- name: Distribute SSH public key to target host
  hosts: prodserver
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Add the public key to authorized_keys
      lineinfile:
        path: ~/.ssh/authorized_keys
        line: "{{ hostvars['source_host']['ssh_pub_key'].stdout }}"
        create: yes
        mode: '0600'
