# This will be launched from devserver
auth:
  ssh_user: appuser
  ssh_private_key: ~/.ssh/cluster-key
cluster_name: default
cluster_synced_files: []
docker:
  container_name: ray_container
  image: rayproject/ray:latest
  pull_before_run: true
  run_options:
  - --ulimit nofile=65536:65536
file_mounts: {}
file_mounts_sync_continuously: false
head_setup_commands: []
head_start_ray_commands:
- ray stop
- ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
idle_timeout_minutes: 5
initialization_commands: []
provider:
  head_ip: <dev_ip>
  type: local
  worker_ips: [<worker1_ip>, <worker2_ip>, <worker3_ip>]
#  - 146.235.197.185
rsync_exclude:
- '**/.git'
- '**/.git/**'
rsync_filter:
- .gitignore
setup_commands: []
upscaling_speed: 1.0
worker_setup_commands: []
worker_start_ray_commands:
- ray stop
- ray start --address=$RAY_HEAD_IP:6379